#!/bin/bash
set -e

# Generated by Project Packager
# Tue Dec 16 15:36:29 GMT 2025

# ============================================
# Project Installation Script
# Generated: 2026-02-26 18:00:19
# Source: src
# ============================================

# SAFETY CHECK - Only create files, don't execute anything
if [ "$1" != "--extract-only" ]; then
    echo "Usage: $0 --extract-only"
    echo "This script only extracts files, doesn't build or execute them."
    echo "Run with: $0 --extract-only"
    exit 1
fi

echo "📦 Project Packager v1.0"
echo "========================="
echo ""

# Create directory structure
echo "📁 Creating directories..."
mkdir -p "assets"
mkdir -p "assets/images"
mkdir -p "components"
mkdir -p "contexts"
mkdir -p "hooks"
mkdir -p "pages"
mkdir -p "pages/VideoDetails"
mkdir -p "utils"
echo ""

# Create files
echo "📄 Creating files..."
# App.jsx (1.2 KB)
cat <<EOL > "App.jsx"
// pages
import Home from "./pages/Home";
import VideoDetails from "./pages/VideoDetails/VideoDetails";
import ChannelDetails from "./pages/ChannelDetails";
import Search from "./pages/Search";
import Error from "./pages/Error";
import PlaylistDetails from "./pages/PlaylistDetails";
// components
import Navbar from "./components/Navbar";

// context provider
import { YoutubeContextProvider } from "./contexts/YoutubeContext";

// react router dom
import { BrowserRouter, Routes, Route } from "react-router-dom";

function App() {
  return (
    <YoutubeContextProvider>
      <div className="bg-cBlack min-h-screen">
        <BrowserRouter>
          <Navbar />
          <Routes>
            <Route exact path="/" element={<Home />} />
            <Route path="/video/:videoId" element={<VideoDetails />} />
            <Route path="/channel/:channelId" element={<ChannelDetails />} />
            <Route path="/search/:searchQuery" element={<Search />} />
            <Route path="/playlist/:playlistId" element={<PlaylistDetails />} />
            <Route path="*" element={<Error />} />
          </Routes>
        </BrowserRouter>
      </div>
    </YoutubeContextProvider>
  );
}

export default App;

EOL

# components/Categories.jsx (1.7 KB)
cat <<EOL > "components/Categories.jsx"
import React from "react";
import { categories } from "../utils/constants";
import ChannelSidebar from "./ChannelSidebar";
import PlaylistSidebar from "./PlaylistSidebar";
import useYoutubeContext from "../hooks/useYoutubeContext";

const Categories = () => {
  const { activeCategory, setActiveCategory } = useYoutubeContext();

  return (
    <div className="w-full md:w-1/5 md:h-[85vh] md:overflow-y-auto md:border-r-2 border-cGray sticky left-0 bg-cBlack scrollbar-hide">
      {/* Categories Section */}
      <div className="flex flex-row md:flex-col overflow-x-scroll md:overflow-x-visible whitespace-nowrap md:whitespace-normal scroll-smooth scrollbar-hide py-2 md:py-3 px-2 md:px-3">
        {categories.map((category, index) => (
          <div
            key={index}
            className={\\`inline-block md:block px-3 py-2 md:px-4 md:py-3 mr-2 md:mr-0 mb-0 md:mb-2 cursor-pointer bg-cGray md:hover:bg-cGray duration-300 rounded-lg font-bold \\${
              category.name === activeCategory
                ? "bg-white text-cGray md:text-white md:bg-cGray"
                : "text-white md:bg-transparent"
            }\\`}
            onClick={() => setActiveCategory(category.name)}
          >
            <div className="flex items-center gap-2 md:gap-3">
              <span className="text-lg md:text-xl flex-shrink-0">
                {category.icon}
              </span>
              <span className="text-sm md:text-base truncate">
                {category.name}
              </span>
            </div>
          </div>
        ))}
      </div>

      {/* Followed Sections - Controlled spacing */}
      <div className="flex flex-col">
        <ChannelSidebar />
        <PlaylistSidebar />
      </div>
    </div>
  );
};

export default Categories;

EOL

# components/ChannelSidebar.jsx (990 bytes)
cat <<EOL > "components/ChannelSidebar.jsx"
import React from "react";
import { Link } from "react-router-dom";
import { FEATURED_CHANNELS } from "../utils/channels";
import { FaUserCircle } from "react-icons/fa";

const ChannelSidebar = () => {
  return (
    <div className="px-2 md:px-3">
      <div className="flex flex-row md:flex-col gap-1 md:gap-2 overflow-x-auto md:overflow-x-visible py-1 md:py-2 scrollbar-hide">
        {FEATURED_CHANNELS.map((channel, index) => (
          <Link
            key={index}
            to={\\`/channel/\\${channel.handle}\\`}
            className="flex items-center gap-2 px-2 md:px-3 py-1.5 md:py-2 bg-cGray rounded-lg hover:bg-gray-700 transition-colors min-w-[120px] md:min-w-0"
          >
            <FaUserCircle className="text-base md:text-xl text-gray-400 flex-shrink-0" />
            <span className="text-white text-xs md:text-sm truncate">
              {channel.name}
            </span>
          </Link>
        ))}
      </div>
    </div>
  );
};

export default ChannelSidebar;

EOL

# components/Navbar.jsx (1.5 KB)
cat <<EOL > "components/Navbar.jsx"
import React from "react";
import { Link } from "react-router-dom";
import SearchBar from "./SearchBar";

const Navbar = () => {
  return (
    <nav className="flex items-center justify-between px-1 sm:px-3 md:px-8 py-2 md:py-3 sticky w-full top-0 z-10 bg-cBlack shadow-md overflow-hidden">
      {/* Left logo - visible */}
      <Link to="/" className="flex-shrink-0">
        <div className="flex text-2xl sm:text-3xl md:text-5xl cursor-pointer">
          <img
            src="https://cdn.sdappnet.cloud/rtx/images/youtube-icon.png"
            style={{ height: "28px", width: "auto" }}
            alt="YouTube Logo"
            className="sm:h-[32px] md:h-[36px]"
          />
        </div>
      </Link>

      {/* Searchbar - centered and fills most of the space on mobile */}
      <div className="flex-1 flex justify-center px-0.5 sm:px-2">
        <div className="w-full max-w-[90%] xs:max-w-[85%] sm:max-w-[70%] md:max-w-[60%] lg:max-w-[50%] xl:max-w-[40%]">
          <SearchBar />
        </div>
      </div>

      {/* Right logo - invisible but maintains layout */}
      <Link
        to="/"
        className="flex-shrink-0 opacity-0 pointer-events-none"
        aria-hidden="true"
      >
        <div className="flex text-2xl sm:text-3xl md:text-5xl cursor-pointer">
          <img
            src="https://cdn.sdappnet.cloud/rtx/images/youtube-icon.png"
            style={{ height: "28px", width: "auto" }}
            alt=""
            className="sm:h-[32px] md:h-[36px]"
          />
        </div>
      </Link>
    </nav>
  );
};

export default Navbar;

EOL

# components/PlaylistCard.jsx (1.3 KB)
cat <<EOL > "components/PlaylistCard.jsx"
// components/PlaylistCard.jsx
import React from "react";
import { Link } from "react-router-dom";
import { FaList } from "react-icons/fa";

const PlaylistCard = ({ playlist }) => {
  const {
    id,
    snippet: { title, thumbnails, channelTitle, publishedAt },
    contentDetails: { itemCount },
  } = playlist;

  return (
    <Link to={\\`/playlist/\\${id}\\`}>
      <div className="w-[300px] md:w-[320px] hover:opacity-80 duration-300 cursor-pointer">
        <div className="relative">
          <img
            className="rounded-xl w-full h-[170px] md:h-[210px] object-cover"
            src={thumbnails.medium.url}
            alt={title}
          />
          <div className="absolute bottom-2 right-2 bg-black bg-opacity-80 px-2 py-1 rounded flex items-center gap-1">
            <FaList className="text-sm" />
            <span className="text-xs">{itemCount}</span>
          </div>
        </div>

        <div className="p-2">
          <h3 className="font-semibold text-sm md:text-base line-clamp-2">
            {title}
          </h3>
          <p className="text-xs text-gray-400 mt-1">{channelTitle}</p>
          <p className="text-xs text-gray-500">
            {new Date(publishedAt).toLocaleDateString()}
          </p>
        </div>
      </div>
    </Link>
  );
};

export default PlaylistCard;

EOL

# components/PlaylistSidebar.jsx (1.2 KB)
cat <<EOL > "components/PlaylistSidebar.jsx"
import React from "react";
import { Link } from "react-router-dom";
import { FEATURED_PLAYLISTS } from "../utils/playlists";
import { FaList } from "react-icons/fa";

const PlaylistSidebar = () => {
  return (
    <div className="px-2 md:px-3">
      <div className="flex flex-row md:flex-col gap-1 md:gap-2 overflow-x-auto md:overflow-x-visible py-1 md:py-2 scrollbar-hide">
        {FEATURED_PLAYLISTS.map((playlist, index) => (
          <Link
            key={index}
            to={\\`/playlist/\\${playlist.id}\\`}
            className="flex items-center gap-2 px-2 md:px-3 py-1.5 md:py-2 bg-cGray rounded-lg hover:bg-gray-700 transition-colors min-w-[120px] md:min-w-0"
          >
            <FaList className="text-xs md:text-sm text-gray-400 flex-shrink-0" />
            <div className="flex flex-col overflow-hidden">
              <span className="text-white text-xs md:text-sm truncate">
                {playlist.name}
              </span>
              <span className="text-gray-500 text-[10px] md:text-xs truncate">
                {playlist.channel}
              </span>
            </div>
          </Link>
        ))}
      </div>
    </div>
  );
};

export default PlaylistSidebar;

EOL

# components/SearchBar.jsx (1.2 KB)
cat <<EOL > "components/SearchBar.jsx"
import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { AiOutlineSearch } from "react-icons/ai";

const SearchBar = () => {
  const [search, setSearch] = useState("");
  const navigate = useNavigate();

  return (
    <form
      className="flex items-center bg-cGray rounded-full w-full h-7 sm:h-8 md:h-10"
      onSubmit={(e) => {
        e.preventDefault();
        if (search.trim()) {
          navigate(\\`/search/\\${search}\\`);
          setSearch("");
        }
      }}
    >
      <input
        type="text"
        placeholder="Search"
        className="px-2 py-0 h-full w-full outline-none focus:outline-blue-800 text-white bg-transparent rounded-l-full text-xs sm:text-sm md:text-base min-w-0"
        value={search}
        onChange={(e) => setSearch(e.target.value)}
      />
      <button
        type="submit"
        className="h-full px-2 md:px-3 flex items-center justify-center text-sm md:text-base cursor-pointer hover:bg-gray-700 rounded-r-full transition-colors flex-shrink-0"
      >
        <AiOutlineSearch
          color="#fff"
          className="w-3.5 h-3.5 sm:w-4 sm:h-4 md:w-5 md:h-5"
        />
      </button>
    </form>
  );
};

export default SearchBar;

EOL

# components/VideoCard.jsx (3.7 KB)
cat <<EOL > "components/VideoCard.jsx"
import React from "react";
import { useNavigate } from "react-router-dom"; // Add this import

// Helper function to create embed URL (matching your Tampermonkey script)
const createEmbedUrl = (videoId) => {
  const code = btoa(videoId)
    .replace(/\\+/g, "-")
    .replace(/\\//g, "_")
    .replace(/=+\\$/, "");
  return \\`https://ytembedxyz.netlify.app?\\${code}\\`;
};

// YouTube thumbnail quality options
const THUMBNAIL_QUALITIES = {
  maxres: "maxresdefault.jpg", // 1280x720 (if available)
  standard: "sddefault.jpg", // 640x480 (if available)
  high: "hqdefault.jpg", // 480x360
  medium: "mqdefault.jpg", // 320x180
  default: "default.jpg", // 120x90
};

// Get thumbnail URL with fallback chain
const getThumbnailUrl = (thumbnails, preferredQuality = "maxres") => {
  if (!thumbnails) return null;

  // If the preferred quality exists, use it
  if (thumbnails[preferredQuality]?.url) {
    return thumbnails[preferredQuality].url;
  }

  // Otherwise, try other qualities in order
  const qualityOrder = ["maxres", "standard", "high", "medium", "default"];
  for (const quality of qualityOrder) {
    if (thumbnails[quality]?.url) {
      return thumbnails[quality].url;
    }
  }

  return null;
};

const VideoCard = ({ video, preferredQuality = "maxres" }) => {
  const navigate = useNavigate(); // Add this hook

  // Safe navigation with fallbacks
  const videoId = video?.id?.videoId;
  const snippet = video?.snippet || {};

  // Get thumbnail with quality preference
  const thumbnails = snippet.thumbnails || {};
  const thumbnailUrl =
    getThumbnailUrl(thumbnails, preferredQuality) ||
    "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimages.pond5.com%2Fyoutube-video-player-transparent-background-footage-279015961_iconl.jpeg&f=1&nofb=1&ipt=a6bb954cb2582c2769cf7a2b709900e713a5c47d4ca09a5fc540ed9e680dadcb";

  const title = snippet.title || "Untitled Video";
  const channelTitle = snippet.channelTitle || "Unknown Channel";

  const handleOpenInNewTab = (e) => {
    e.preventDefault();
    if (videoId) {
      window.open(createEmbedUrl(videoId), "_blank");
    }
  };

  const handleChannelClick = (e) => {
    e.stopPropagation(); // Prevent video card click
    // Navigate to channel page using React Router
    if (snippet?.channelId) {
      navigate(\\`/channel/\\${snippet.channelId}\\`);
    } else if (snippet?.channelTitle) {
      // Fallback - try to navigate using channel title as handle
      // Remove spaces and special characters to create a handle
      const handle = snippet.channelTitle
        .replace(/\\s+/g, "")
        .replace(/[^a-zA-Z0-9]/g, "");
      navigate(\\`/channel/@\\${handle}\\`);
    }
  };

  return (
    <div className="w-[300px] md:w-[320px] h-[300px] md:h-[320px] hover:opacity-80 duration-300 cursor-pointer">
      <div onClick={handleOpenInNewTab}>
        <img
          className="rounded-xl hover:rounded-none w-full h-[170px] md:h-[210px] object-cover duration-300"
          src={thumbnailUrl}
          alt={title}
          loading="lazy"
          onError={(e) => {
            e.target.src =
              "https://via.placeholder.com/320x180?text=No+Thumbnail";
          }}
        />

        <div className="p-1">
          <h2 className="text-md mt-2">
            {title.length > 70 ? title.slice(0, 70) + "..." : title}
          </h2>

          {/* Channel - clicking this won't open video */}
          <div onClick={handleChannelClick}>
            <p className="text-sm text-gray-400 py-2 font-semibold hover:text-white cursor-pointer">
              {channelTitle.length > 30
                ? channelTitle.slice(0, 30) + "..."
                : channelTitle}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default VideoCard;

EOL

# components/Videos.jsx (360 bytes)
cat <<EOL > "components/Videos.jsx"
import { useEffect } from "react";
import VideoCard from "./VideoCard";

const Videos = ({ videos }) => {
  return (
    <div className="p-3 text-white flex flex-wrap items-center justify-around gap-y-1 sm:gap-y-3 md:gap-y-10">
      {videos?.map((video, i) => (
        <VideoCard key={i} video={video} />
      ))}
    </div>
  );
};

export default Videos;

EOL

# components/VideosLoader.jsx (719 bytes)
cat <<EOL > "components/VideosLoader.jsx"
import React from "react";
import Skeleton from "react-loading-skeleton";
import "react-loading-skeleton/dist/skeleton.css";

const VideosLoader = () => {
  return (
    <div className="p-3 flex flex-wrap items-center justify-around gap-y-1 sm:gap-y-3 md:gap-y-10">
      {[...Array(20)].map((_, i) => (
        <div
          key={i}
          className="w-[300px] md:w-[320px] h-[300px] md:h-[320px]"
        >
          <Skeleton className="w-full h-[170px] md:h-[210px] !rounded-xl" />
          <div className="p-1">
            <Skeleton className="!w-3/4 h-6 mt-2" />
            <Skeleton className="!w-1/2 h-4 mt-2" />
          </div>
        </div>
      ))}
    </div>
  );
};

export default VideosLoader;

EOL

echo "  Processed 10/24 files..."
# contexts/YoutubeContext.jsx (10.5 KB)
cat <<EOL > "contexts/YoutubeContext.jsx"
import axios from "axios";
import React, { createContext, useState } from "react";

export const YoutubeContext = createContext();

// CONFIGURABLE LIMITS - Change these as needed!
const DEFAULTS = {
  SEARCH_MAX: 500, // Max search results (default 48)
  CHANNEL_VIDEOS_MAX: 5000, // Max videos from channel
  PLAYLIST_ITEMS_MAX: 5000, // Max playlist items
  RELATED_VIDEOS_MAX: 48, // Related videos max
  COMMENTS_MAX: 100, // Comments max if you add later
};

const YoutubeContextProvider = ({ children }) => {
  const [activeCategory, setActiveCategory] = useState("New");

  // Google YouTube API v3 base URL
  const BASE_URL = "https://www.googleapis.com/youtube/v3";

  // Helper function to get channel ID from handle
  const getChannelIdFromHandle = async (handle) => {
    try {
      const API_KEY = import.meta.env.VITE_GOOGLE_API_KEY;

      const cleanHandle = handle.replace("@", "").trim();

      const response = await axios.get(\\`\\${BASE_URL}/channels\\`, {
        params: {
          part: "id",
          forHandle: cleanHandle,
          key: API_KEY,
        },
      });

      if (response.data.items && response.data.items.length > 0) {
        const channelId = response.data.items[0].id;
        console.log(\\`✅ Resolved \\${handle} → \\${channelId}\\`);
        return channelId;
      }

      console.warn(\\`❌ No channel found for handle: \\${handle}\\`);
      return null;
    } catch (error) {
      console.error(
        "Error resolving channel handle:",
        error.response?.data || error.message
      );
      return null;
    }
  };

  // NEW: Get the uploads playlist ID for a channel
  const getUploadsPlaylistId = async (channelId) => {
    try {
      const API_KEY = import.meta.env.VITE_GOOGLE_API_KEY;

      const response = await axios.get(\\`\\${BASE_URL}/channels\\`, {
        params: {
          key: API_KEY,
          id: channelId,
          part: "contentDetails",
        },
      });

      if (response.data.items && response.data.items.length > 0) {
        // The uploads playlist ID is in relatedPlaylists.uploads
        const uploadsPlaylistId =
          response.data.items[0].contentDetails.relatedPlaylists.uploads;
        console.log(
          \\`✅ Got uploads playlist: \\${uploadsPlaylistId} for channel: \\${channelId}\\`
        );
        return uploadsPlaylistId;
      }

      return null;
    } catch (error) {
      console.error("Error getting uploads playlist:", error);
      return null;
    }
  };

  // UPDATED: Fetch ALL channel videos using the uploads playlist (more efficient and gets ALL videos)
  const fetchChannelVideos = async (
    channelIdentifier,
    maxResults = DEFAULTS.CHANNEL_VIDEOS_MAX
  ) => {
    try {
      const API_KEY = import.meta.env.VITE_GOOGLE_API_KEY;

      // Resolve channel ID if handle was provided
      let channelId = channelIdentifier;
      if (
        typeof channelIdentifier === "string" &&
        channelIdentifier.includes("@")
      ) {
        channelId = await getChannelIdFromHandle(channelIdentifier);
        if (!channelId) return null;
      }

      // Get the uploads playlist ID first
      const uploadsPlaylistId = await getUploadsPlaylistId(channelId);
      if (!uploadsPlaylistId) {
        console.error("Could not find uploads playlist for channel");
        return null;
      }

      // Now fetch all videos from the uploads playlist with pagination
      let allVideos = [];
      let nextPageToken = null;
      let totalFetched = 0;

      console.log(
        \\`📦 Fetching ALL videos for channel: \\${channelId} (max: \\${maxResults})\\`
      );

      do {
        const params = {
          key: API_KEY,
          part: "snippet",
          playlistId: uploadsPlaylistId,
          maxResults: 50, // API max per page
        };

        if (nextPageToken) {
          params.pageToken = nextPageToken;
        }

        const response = await axios.get(\\`\\${BASE_URL}/playlistItems\\`, {
          params,
        });

        if (response.data.items) {
          // Transform playlist items to match the video format expected by components
          const transformedVideos = response.data.items.map((item) => ({
            id: { videoId: item.snippet.resourceId.videoId },
            snippet: {
              ...item.snippet,
              // Ensure we have channelId (it's in the playlist item)
              channelId: item.snippet.channelId,
            },
          }));

          allVideos = [...allVideos, ...transformedVideos];
          nextPageToken = response.data.nextPageToken;

          console.log(\\`📥 Fetched \\${allVideos.length} videos so far...\\`);
        } else {
          break;
        }

        // Stop if we've reached the configured max
        if (allVideos.length >= maxResults) {
          console.log(\\`✅ Reached max results limit: \\${maxResults}\\`);
          break;
        }
      } while (nextPageToken);

      console.log(
        \\`✅ Total fetched: \\${allVideos.length} videos for channel \\${channelId}\\`
      );

      // Return in the same format as the search endpoint for compatibility
      return {
        items: allVideos,
        totalCount: allVideos.length,
        nextPageToken: nextPageToken,
      };
    } catch (error) {
      console.error(
        "Error fetching channel videos:",
        error.response?.data || error.message
      );
      return null;
    }
  };

  // Fetch ALL playlist items with pagination and configurable max
  const fetchAllPlaylistItems = async (
    playlistId,
    maxResults = DEFAULTS.PLAYLIST_ITEMS_MAX
  ) => {
    try {
      const API_KEY = import.meta.env.VITE_GOOGLE_API_KEY;
      let allItems = [];
      let nextPageToken = null;

      console.log(
        \\`📦 Fetching playlist: \\${playlistId} (max: \\${maxResults} videos)\\`
      );

      do {
        const params = {
          key: API_KEY,
          part: "snippet,contentDetails",
          playlistId: playlistId,
          maxResults: 50, // API max per page
        };

        if (nextPageToken) {
          params.pageToken = nextPageToken;
        }

        const response = await axios.get(\\`\\${BASE_URL}/playlistItems\\`, {
          params,
        });

        if (response.data.items) {
          allItems = [...allItems, ...response.data.items];
          nextPageToken = response.data.nextPageToken;

          console.log(\\`📥 Fetched \\${allItems.length} videos so far...\\`);
        } else {
          break;
        }

        // Stop if we've reached the configured max
        if (allItems.length >= maxResults) {
          console.log(\\`✅ Reached max results limit: \\${maxResults}\\`);
          break;
        }
      } while (nextPageToken);

      console.log(\\`✅ Total fetched: \\${allItems.length} videos\\`);
      return {
        items: allItems,
        totalCount: allItems.length,
        hasMore: !!nextPageToken && allItems.length < maxResults,
        nextPageToken: nextPageToken,
      };
    } catch (error) {
      console.error(
        "Error fetching playlist items:",
        error.response?.data || error.message
      );
      return null;
    }
  };

  // Main fetch function with per-call overrides
  const fetchData = async (input, type = "search", options = {}) => {
    try {
      const API_KEY = import.meta.env.VITE_GOOGLE_API_KEY;

      if (!API_KEY) {
        console.error("❌ Google API key is missing!");
        return null;
      }

      // Channel videos - now uses uploads playlist method
      if (type === "channelVideos") {
        const maxResults = options.maxResults || DEFAULTS.CHANNEL_VIDEOS_MAX;
        return await fetchChannelVideos(input, maxResults);
      }

      // Regular search - with custom max
      if (type === "search") {
        const maxResults = options.maxResults || DEFAULTS.SEARCH_MAX;
        const response = await axios.get(\\`\\${BASE_URL}/search\\`, {
          params: {
            key: API_KEY,
            q: input,
            part: "snippet",
            type: "video",
            maxResults: maxResults,
          },
        });
        return response.data;
      }

      // Playlist details
      if (type === "playlist") {
        const response = await axios.get(\\`\\${BASE_URL}/playlists\\`, {
          params: {
            key: API_KEY,
            part: "snippet,contentDetails",
            id: input,
          },
        });
        return response.data;
      }

      // Playlist items with pagination and custom max
      if (type === "playlistItems") {
        const maxResults = options.maxResults || DEFAULTS.PLAYLIST_ITEMS_MAX;
        return await fetchAllPlaylistItems(input, maxResults);
      }

      // Video details
      if (type === "videos") {
        const response = await axios.get(\\`\\${BASE_URL}/videos\\`, {
          params: {
            key: API_KEY,
            id: input,
            part: "snippet,statistics",
          },
        });
        return response.data;
      }

      // Related videos (for video details page)
      if (type === "related") {
        const maxResults = options.maxResults || DEFAULTS.RELATED_VIDEOS_MAX;
        const response = await axios.get(\\`\\${BASE_URL}/search\\`, {
          params: {
            key: API_KEY,
            relatedToVideoId: input,
            part: "snippet",
            type: "video",
            maxResults: maxResults,
          },
        });
        return response.data;
      }

      // Channel details
      if (type === "channels") {
        let channelId = input;
        if (typeof input === "string" && input.includes("@")) {
          channelId = await getChannelIdFromHandle(input);
          if (!channelId) return null;
        }

        const response = await axios.get(\\`\\${BASE_URL}/channels\\`, {
          params: {
            key: API_KEY,
            id: channelId,
            part: "snippet,statistics,brandingSettings",
          },
        });
        return response.data;
      }

      return null;
    } catch (error) {
      console.error(
        "❌ YouTube API Error:",
        error.response?.data || error.message
      );
      return null;
    }
  };

  function convertNumber(number) {
    if (!number) return "0";
    const num = parseInt(number);

    if (num >= 1000000) {
      return num % 1000000 === 0
        ? num / 1000000 + "M"
        : (num / 1000000).toFixed(1) + "M";
    } else if (num >= 1000) {
      return num % 1000 === 0
        ? num / 1000 + "K"
        : (num / 1000).toFixed(1) + "K";
    } else {
      return num.toString();
    }
  }

  const value = {
    activeCategory,
    setActiveCategory,
    fetchData,
    convertNumber,
    DEFAULTS, // Expose defaults so components can see them
  };

  return (
    <YoutubeContext.Provider value={value}>{children}</YoutubeContext.Provider>
  );
};

export { YoutubeContextProvider };

EOL

# hooks/useYoutubeContext.js (214 bytes)
cat <<EOL > "hooks/useYoutubeContext.js"
import React, { useContext } from "react";
import { YoutubeContext } from "../contexts/YoutubeContext";

const useYoutubeContext = () => {
  return useContext(YoutubeContext);
};

export default useYoutubeContext;

EOL

# index.css (797 bytes)
cat <<EOL > "index.css"
@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  font-family: 'Roboto', sans-serif;
}

/* Hide scrollbar for Chrome, Safari and Opera */
.scrollbar-hide::-webkit-scrollbar {
  display: none;
}

/* Hide scrollbar for IE, Edge and Firefox */
.scrollbar-hide {
  -ms-overflow-style: none; /* IE and Edge */
  scrollbar-width: none; /* Firefox */
}

/* custom scrollbar */
::-webkit-scrollbar {
  width: 14px;
  background-color: #1D131C;
}

::-webkit-scrollbar-track {
  background-color: #e4e4e4;
  border-radius: 100px;
}

::-webkit-scrollbar-thumb {
  background-color: rgb(114, 113, 113);
  box-shadow: inset 2px 2px 5px 0 rgba(#fff, 0.5);
  border-radius: 100px;
  transition: all 0.3s ease-in-out;
}

::-webkit-scrollbar-thumb:hover {
  background-color: rgb(80, 80, 80);
}

EOL

# main.jsx (231 bytes)
cat <<EOL > "main.jsx"
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)

EOL

# pages/ChannelDetails.jsx (3.7 KB)
cat <<EOL > "pages/ChannelDetails.jsx"
import React, { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import useYoutubeContext from "../hooks/useYoutubeContext";
// components
import Videos from "../components/Videos";
import VideosLoader from "../components/VideosLoader";
// skeleton
import Skeleton from "react-loading-skeleton";
// react-helmet
import { Helmet, HelmetProvider } from "react-helmet-async";

const ChannelDetails = () => {
  const { channelId } = useParams();
  const { fetchData, convertNumber } = useYoutubeContext();
  const [channelDetail, setChannelDetail] = useState([]);
  const [videos, setVideos] = useState([]);
  const [loading, setLoading] = useState(true);

  // In the useEffect, update the fetchData calls:

  // In pages/ChannelDetails.jsx, update the useEffect:

  useEffect(() => {
    window.scrollTo(0, 0);

    // If channelId contains @, fetch by handle, otherwise use as ID
    const fetchChannelData = async () => {
      setLoading(true);

      // Fetch channel details (fetchData handles @ automatically)
      const channelData = await fetchData(channelId, "channels");
      setChannelDetail(channelData?.items[0]);

      // Get the actual channel ID for fetching videos
      let actualChannelId = channelId;
      if (channelId.includes("@")) {
        // We need to resolve it first - fetchData will do this internally
        // But for videos, we need the resolved ID
        const resolvedData = await fetchData(channelId, "channels");
        actualChannelId = resolvedData?.items[0]?.id;
      }

      // Fetch channel videos
      const videosData = await fetchData(
        actualChannelId || channelId,
        "channelVideos"
      );
      setVideos(videosData?.items || []);
      setLoading(false);
    };

    fetchChannelData();
  }, [channelId]);
  // const {
  //   brandingSettings: { image },
  //   snippet: { title, customUrl, thumbnails },
  //   statistics: { subscriberCount, videoCount },
  // } = channelDetail;

  return (
    <HelmetProvider>
      <div className="text-white">
        <Helmet>
          <title>{\\`\\${channelDetail?.snippet?.title} - YouTube\\`}</title>
        </Helmet>

        <div className="flex flex-col md:flex-row items-center py-3 px-2 sm:px-6 md:px-12 lg:px-20">
          {channelDetail?.snippet?.thumbnails?.default?.url ? (
            <img
              src={channelDetail?.snippet?.thumbnails?.default?.url}
              alt={channelDetail?.snippet?.title}
              className="rounded-full h-[100px] w-[100px] md:w-[128px] md:h-[128px]"
            />
          ) : (
            <Skeleton className="rounded-full h-[100px] w-[100px] md:w-[128px] md:h-[128px]" />
          )}

          <div className="flex flex-col items-center md:items-start p-3">
            <h1 className="font-bold text-xl md:text-2xl py-2 md:py-1">
              {channelDetail?.snippet?.title || (
                <Skeleton className="w-[200px]" />
              )}
            </h1>

            <div className="flex text-gray-300 space-x-2 sm:space-x-3 md:space-x-4 text-[11px] sm:text-[13px] md:text-[16px]">
              <p>
                {channelDetail?.snippet?.customUrl || (
                  <Skeleton className="w-[70px]" />
                )}
              </p>
              <p>
                {convertNumber(
                  parseInt(channelDetail?.statistics?.subscriberCount || 0)
                )}{" "}
                subscribers
              </p>
              <p>
                {convertNumber(channelDetail?.statistics?.videoCount) || 0}{" "}
                videos
              </p>
            </div>
          </div>
        </div>
        <hr className="my-5" />
        {loading ? <VideosLoader /> : <Videos videos={videos} />}
      </div>
    </HelmetProvider>
  );
};

export default ChannelDetails;

EOL

# pages/Error.jsx (547 bytes)
cat <<EOL > "pages/Error.jsx"
import React from "react";
import monkey from "../assets/images/monkey.png";
import { Helmet } from "react-helmet";

const Error = () => {
  return (
    <div className="text-white min-h-[85vh] flex items-center flex-col justify-center md:text-xl text-center p-3">
      <Helmet>
        <title>404 Not Found</title>
      </Helmet>
      <img src={monkey} alt="Page wasn't found" className="p-5" />
      <p>This page isn't available. Sorry about that.</p>
      <p>Try searching for something else.</p>
    </div>
  );
};

export default Error;

EOL

# pages/Home.jsx (2.6 KB)
cat <<EOL > "pages/Home.jsx"
import React, { useEffect, useState } from "react";
import useYoutubeContext from "../hooks/useYoutubeContext";
import Categories from "../components/Categories";
import Videos from "../components/Videos";
import VideosLoader from "../components/VideosLoader";
import { Helmet, HelmetProvider } from "react-helmet-async";
import { FEATURED_CHANNELS } from "../utils/channels";

const Home = () => {
  const { activeCategory, fetchData } = useYoutubeContext();
  const [videos, setVideos] = useState([]);
  const [loading, setLoading] = useState(true);

  // In Home.jsx, update the fetchVideos function:

  useEffect(() => {
    window.scrollTo(0, 0);
    setVideos([]);
    setLoading(true);

    const fetchVideos = async () => {
      try {
        if (activeCategory === "New") {
          // Fetch channel videos but limit each channel to 10-20 recent videos
          const channelPromises = FEATURED_CHANNELS.map((channel) =>
            fetchData(channel.handle, "channelVideos", {
              maxResults: 50, // ← Only get 20 most recent per channel
            })
          );

          const results = await Promise.all(channelPromises);

          // Combine all videos and sort by date
          const allVideos = results
            .flatMap((result) => result?.items || [])
            .sort(
              (a, b) =>
                new Date(b.snippet.publishedAt) -
                new Date(a.snippet.publishedAt)
            )
            .slice(0, 100); // ← Optional: limit total to 100 videos

          console.log("✅ Found channel videos:", allVideos.length);
          setVideos(allVideos);
        } else {
          // Regular category search - limit to 48
          const data = await fetchData(activeCategory, "search", {
            maxResults: 48,
          });
          setVideos(data?.items || []);
        }
        setLoading(false);
      } catch (error) {
        console.error("Error fetching videos:", error);
        setLoading(false);
      }
    };

    fetchVideos();
  }, [activeCategory]);

  return (
    <HelmetProvider>
      <div className="flex flex-col md:flex-row p-2 md:p-3 min-h-screen">
        <Helmet>
          <title>
            {activeCategory === "New" ? "Home" : activeCategory} - YouTube
          </title>
        </Helmet>
        <Categories />
        <div className="w-full md:w-4/5">
          {loading ? (
            <VideosLoader />
          ) : videos.length > 0 ? (
            <Videos videos={videos} />
          ) : (
            <div className="text-white text-center py-10">No videos found</div>
          )}
        </div>
      </div>
    </HelmetProvider>
  );
};

export default Home;

EOL

# pages/PlaylistDetails.jsx (2.7 KB)
cat <<EOL > "pages/PlaylistDetails.jsx"
// pages/PlaylistDetails.jsx (you'll need to create this file)
import React, { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import useYoutubeContext from "../hooks/useYoutubeContext";
import Videos from "../components/Videos";
import VideosLoader from "../components/VideosLoader";
import { Helmet, HelmetProvider } from "react-helmet-async";

const PlaylistDetails = () => {
  const { playlistId } = useParams();
  const { fetchData } = useYoutubeContext();
  const [playlist, setPlaylist] = useState(null);
  const [videos, setVideos] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    window.scrollTo(0, 0);
    setLoading(true);

    const fetchPlaylistData = async () => {
      try {
        // Fetch playlist details
        const playlistData = await fetchData(playlistId, "playlist");
        setPlaylist(playlistData?.items[0]);

        // Fetch playlist videos
        const videosData = await fetchData(playlistId, "playlistItems");

        // Transform playlist items to match VideoCard format with proper null checking
        const transformedVideos =
          videosData?.items
            ?.map((item) => {
              const snippet = item?.snippet || {};

              // Ensure thumbnails object exists
              if (!snippet.thumbnails) {
                snippet.thumbnails = {
                  medium: {
                    url: "https://via.placeholder.com/320x180?text=No+Thumbnail",
                  },
                };
              }

              return {
                id: { videoId: snippet?.resourceId?.videoId },
                snippet: snippet,
              };
            })
            .filter((video) => video.id.videoId) || []; // Filter out items without videoId

        setVideos(transformedVideos);
      } catch (error) {
        console.error("Error fetching playlist:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchPlaylistData();
  }, [playlistId, fetchData]);

  return (
    <HelmetProvider>
      <div className="text-white p-4">
        <Helmet>
          <title>
            {playlist?.snippet?.title || "Playlist"} - YouTube Clone
          </title>
        </Helmet>

        {playlist && (
          <div className="mb-6">
            <h1 className="text-2xl font-bold">{playlist.snippet.title}</h1>
            <p className="text-gray-400 mt-2">{playlist.snippet.description}</p>
            <p className="text-sm text-gray-500 mt-1">
              {playlist.contentDetails?.itemCount} videos
            </p>
          </div>
        )}

        {loading ? <VideosLoader /> : <Videos videos={videos} />}
      </div>
    </HelmetProvider>
  );
};

export default PlaylistDetails;

EOL

# pages/Search.jsx (1.1 KB)
cat <<EOL > "pages/Search.jsx"
import React, { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import useYoutubeContext from "../hooks/useYoutubeContext";
import Videos from "../components/Videos";
import VideosLoader from "../components/VideosLoader";
import { Helmet, HelmetProvider } from "react-helmet-async";

const Search = () => {
  // Capitalized component name
  const { searchQuery } = useParams();
  const { fetchData } = useYoutubeContext();
  const [videos, setVideos] = useState([]); // Fixed variable name
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    window.scrollTo(0, 0);
    setLoading(true);
    // Fix the fetchData call - it now expects (searchQuery, type)
    fetchData(searchQuery, "search").then((data) => {
      setVideos(data?.items || []);
      setLoading(false);
    });
  }, [searchQuery]);

  return (
    <HelmetProvider>
      <div className="py-3">
        <Helmet>
          <title>{\\`\\${searchQuery} - YouTube\\`}</title>
        </Helmet>
        {loading ? <VideosLoader /> : <Videos videos={videos} />}
      </div>
    </HelmetProvider>
  );
};

export default Search; // Default export

EOL

# pages/VideoDetails/VideoDetails.css (350 bytes)
cat <<EOL > "pages/VideoDetails/VideoDetails.css"
.react-player {
  width: 100% !important;
  height: 70vh !important;
}

@media screen and (max-width: 768px) {
  .react-player {
    height: 50vh !important;
  }
}

@media screen and (max-width: 640px) {
  .react-player {
    height: 45vh !important;
  }
}

@media screen and (max-width: 425px) {
  .react-player {
    height: 40vh !important;
  }
}

EOL

echo "  Processed 20/24 files..."
# pages/VideoDetails/VideoDetails.jsx (4.4 KB)
cat <<EOL > "pages/VideoDetails/VideoDetails.jsx"
import React, { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import ReactPlayer from "react-player";
// context
import useYoutubeContext from "../../hooks/useYoutubeContext";
// components
import Videos from "../../components/Videos";
import VideosLoader from "../../components/VideosLoader";
// icons
import { FaCheckCircle } from "react-icons/fa";
import { AiFillLike } from "react-icons/ai";
import { FaShare } from "react-icons/fa";
import { HiScissors } from "react-icons/hi";
// skeleton
import Skeleton from "react-loading-skeleton";
// react-helmet
import { Helmet, HelmetProvider } from "react-helmet-async";
// css
import "./VideoDetails.css";

const VideoDetails = () => {
  const { videoId } = useParams();
  const { fetchData, convertNumber } = useYoutubeContext();
  const [videoDetail, setVideoDetail] = useState(null);
  const [videos, setVideos] = useState(null);
  const [loading, setLoading] = useState(true);

  // In the useEffect, update:
  useEffect(() => {
    window.scrollTo(0, 0);
    setLoading(true);

    // Fix: fetch video details
    fetchData(videoId, "videos").then((data) => {
      setVideoDetail(data?.items[0]);
    });

    // Fix: fetch related videos
    fetchData(videoId, "search").then((data) => {
      setVideos(data?.items || []);
      setLoading(false);
    });
  }, [videoId]);

  // const {
  //   snippet: { title, channelId, channelTitle, description, publishedAt, tags },
  //   statistics: { viewCount, likeCount },
  // } = videoDetail;

  return (
    <HelmetProvider>
      <Helmet>
        <title>{\\`\\${videoDetail?.snippet?.title} - YouTube\\`}</title>
      </Helmet>
      <div className="px-0 md:px-10 lg:px-14 sticky top-0 z-10 md:static md:z-0">
        <ReactPlayer
          url={\\`https://www.youtube.com/watch?v=\\${videoId}\\`}
          className="react-player"
          controls
        />
      </div>
      <div className="px-4 sm:px-6 md:px-10 lg:px-14 py-3 w-full text-white">
        <h1 className="md:font-bold font-semibold md:text-xl text-lg py-4 md:py-5">
          {videoDetail?.snippet?.title || <Skeleton className="w-3/5" />}
        </h1>
        <div className="flex items-center justify-between text-gray-300">
          <Link to={\\`/channel/\\${videoDetail?.snippet?.channelId}\\`}>
            <div className="font-bold flex items-center gap-1 md:gap-2 duration-300 hover:text-gray-100 text-md md:text-lg">
              <div className="w-full">
                {videoDetail?.snippet?.channelTitle || (
                  <Skeleton className="w-[200px]" />
                )}{" "}
              </div>
              <FaCheckCircle color="#ADD8E6" />
            </div>
          </Link>
          <div className="flex items-center sm:space-x-4 lg:space-x-6 xl:space-x-8">
            <button className="flex items-center gap-1 bg-cGray px-3 py-2 rounded-full">
              <AiFillLike color="#ADD8E6" />
              {convertNumber(parseInt(videoDetail?.statistics?.likeCount)) ||
                "123"}
            </button>
            <button className="hidden md:flex items-center gap-1 bg-cGray px-3 py-2 rounded-full">
              <FaShare color="#ADD8E6" />
              Share
            </button>
            <button className="hidden sm:flex items-center gap-1 bg-cGray px-3 py-2 rounded-full">
              <HiScissors color="#ADD8E6" />
              Clip
            </button>
          </div>
        </div>

        {/* description */}
        <div className="bg-cGray py-3 md:py-4 px-4 md:px-5 rounded-md mt-5 md:text-[16px] text-[14px]">
          <p>
            {convertNumber(parseInt(videoDetail?.statistics?.viewCount)) || 0}{" "}
            views • {videoDetail?.snippet?.publishedAt.slice(0, 10)}
          </p>
          <p className="py-3 whitespace-break-spaces overflow-hidden">
            {videoDetail?.snippet?.description.length > 700
              ? videoDetail?.snippet?.description.slice(0, 700) + "..."
              : videoDetail?.snippet?.description}
          </p>
          <p>
            {videoDetail?.snippet?.tags?.map((tag, index) => (
              <a href="#" key={index} className="text-blue-500">
                #{tag} &nbsp;
              </a>
            ))}
          </p>
        </div>

        <div className="w-full py-10 md:py-14">
          {loading ? <VideosLoader /> : <Videos videos={videos} />}
        </div>
      </div>
    </HelmetProvider>
  );
};

export default VideoDetails;

EOL

# utils/channels.js (336 bytes)
cat <<EOL > "utils/channels.js"
// utils/channels.js
export const FEATURED_CHANNELS = [
  {
    handle: "@toastedgaming5739",
    name: "Toasted Gaming",
  },
  { handle: "@XT-qv5vu", name: "Windows XP Gameplay" },
  { handle: "@Flandrew", name: "Flandrew" },
  { handle: "@VideoGameEsoterica", name: "Video Game Esoterica" },

  // Add more channels with handles!
];

EOL

# utils/constants.jsx (674 bytes)
cat <<EOL > "utils/constants.jsx"
// icons
import {
  FaHome as HomeIcon,
  FaCode as CodeIcon,
  FaMusic as MusicNoteIcon,
  FaSchool as SchoolIcon,
  FaGamepad as SportsEsportsIcon,
  FaTv as LiveTvIcon,
  FaDumbbell as FitnessCenterIcon,
  FaTheaterMasks as TheaterComedyIcon,
} from "react-icons/fa";

import {
  MdGraphicEq as GraphicEqIcon,
  MdOndemandVideo as OndemandVideoIcon,
  MdCheckroom as CheckroomIcon,
  MdFaceRetouchingNatural as FaceRetouchingNaturalIcon,
  MdDeveloperMode as DeveloperModeIcon,
} from "react-icons/md";

export const categories = [
  { name: "New", icon: <HomeIcon /> },
  { name: "Coding", icon: <CodeIcon /> },
  ,
  { name: "Gaming", icon: <SportsEsportsIcon /> },
];

EOL

# utils/playlists.js (3.1 KB)
cat <<EOL > "utils/playlists.js"
// utils/playlists.js
export const FEATURED_PLAYLISTS = [
  {
    id: "PLb8oNKiUbnjGUc3_ec-BWBKfnYt3igEcd",
    name: "AVPClassic",
    channel: "IGITeam",
  },
  {
    id: "PLb8oNKiUbnjGRkIsna2Bu7WKEtKU8Z7WE",
    name: "battlefield1942",
    channel: "IGITeam",
  },
  {
    id: "PLb8oNKiUbnjGUBaPcPC0Bxvg8gpEwP_sO",
    name: "codename47",
    channel: "IGITeam",
  },

  {
    id: "PLb8oNKiUbnjEMFUeRC6kttICm4rdqbBED",
    name: "cs1.6server-linux",
    channel: "IGITeam",
  },
  {
    id: "PLb8oNKiUbnjFGRpy3A4vm7XLXu5yo-xZE",
    name: "darkengine",
    channel: "IGITeam",
  },
  {
    id: "PLb8oNKiUbnjESxcNHB2ilO4pIvPnd5gdK",
    name: "decomp projects",
    channel: "IGITeam",
  },
  {
    id: "PLb8oNKiUbnjFIgoAZQL4m-BRzJegThtUV",
    name: "DeltaForceBlackHawkDown",
    channel: "IGITeam",
  },

  {
    id: "PLb8oNKiUbnjGRZp6vAREIMTbxQK0bHdrH",
    name: "doom3",
    channel: "IGITeam",
  },
  {
    id: "PLb8oNKiUbnjH9MZYeI3zRvRXYDSMJkSSZ",
    name: "duke-nukem-forever-2001-unreal-engine-1",
    channel: "IGITeam",
  },
  {
    id: "PLb8oNKiUbnjGgc2IwdJa2nS0meSPLdYYY",
    name: "farcry1",
    channel: "IGITeam",
  },

  {
    id: "PLb8oNKiUbnjEvoX7Xs9qNfncnxlw6NUzG",
    name: "gamestick",
    channel: "IGITeam",
  },
  {
    id: "PLb8oNKiUbnjG2PTtT6mmlNKLhIuDNK7yN",
    name: "goldsrc",
    channel: "IGITeam",
  },
  {
    id: "PLb8oNKiUbnjGBbc5VjRKs2sxSkrcX-1Wc",
    name: "HLAE ( Campath )",
    channel: "IGITeam",
  },

  {
    id: "PLb8oNKiUbnjGbvfVeg_X-tlTApBZJRqfd",
    name: "lego-spyrius",
    channel: "IGITeam",
  },
  {
    id: "PLb8oNKiUbnjFO0_sNfW4A80k9UWjBhVRo",
    name: "LithTech-Jupiter-FX",
    channel: "IGITeam",
  },
  {
    id: "PLb8oNKiUbnjHhz7tZXlTMaJXfUUKrAn4L",
    name: "mafia-ls3d",
    channel: "IGITeam",
  },
  {
    id: "PLb8oNKiUbnjEOt1UAQvIii1GkvhR35oha",
    name: "mafia1",
    channel: "IGITeam",
  },
  {
    id: "PLb8oNKiUbnjHO4DWWBkPRG5lgHQ-nVoyd",
    name: "milkshape3d",
    channel: "IGITeam",
  },
  {
    id: "PLb8oNKiUbnjHErP6Rs6_E-AdCsXBGa3lV",
    name: "mohpa",
    channel: "IGITeam",
  },
  {
    id: "PLb8oNKiUbnjENZQ-1s0bBXGlQTh5GD0r7",
    name: "old_softwares",
    channel: "IGITeam",
  },
  {
    id: "PLb8oNKiUbnjEug75t5V8XUR26jmoyjEvs",
    name: "openjkdf2",
    channel: "IGITeam",
  },

  {
    id: "PLb8oNKiUbnjFWb0B0dfEO_vb9Fw7zmJzG",
    name: "q3radiant",
    channel: "IGITeam",
  },
  {
    id: "PLb8oNKiUbnjG1uQzBMz9AZUk_eKlXG8P0",
    name: "red-faction",
    channel: "IGITeam",
  },
  {
    id: "PLb8oNKiUbnjFl57R1VdS9_vslcAcOYnlA",
    name: "serious sam first encounter editor",
    channel: "IGITeam",
  },
  {
    id: "PLb8oNKiUbnjFZb-_ngusgN37lwBgcrGpn",
    name: "sony-vegas-pro-8",
    channel: "IGITeam",
  },
  {
    id: "PLb8oNKiUbnjEyBhOmiOP_PC71gUQ8xEdg",
    name: "swat3",
    channel: "IGITeam",
  },

  {
    id: "PLb8oNKiUbnjEyAEJ6hqmN4Wjd9KtFNeyD",
    name: "UE3",
    channel: "IGITeam",
  },
  {
    id: "PLb8oNKiUbnjFc3u1dThsYgp_NX3R2olgH",
    name: "vampire_the_masquarade",
    channel: "IGITeam",
  },
  {
    id: "PLb8oNKiUbnjHprmtAjCAv7Kkz8XOX_XRb",
    name: "wineskin",
    channel: "IGITeam",
  },
];

EOL

echo ""
# Display statistics
echo "✅ Project successfully recreated!"
echo "📊 Statistics:"
echo "   • Directories: 8"
echo "   • Files: 24"
echo "   • Skipped: 2"
echo "   • Total size: 0.0 MB"
echo "🏠 Location: $(pwd)"
echo "🚀 Ready to use!"

# End of script

echo "File List"
echo "========="
echo ""
echo "[FOLDER] contexts/"
echo "[JSX   ] contexts/YoutubeContext.jsx (10.53 KiB)"
echo "[FOLDER] utils/"
echo "[JSX   ] utils/constants.jsx (674.0 B)"
echo "[JS    ] utils/playlists.js (3.07 KiB)"
echo "[JS    ] utils/channels.js (336.0 B)"
echo "[FOLDER] components/"
echo "[JSX   ] components/VideoCard.jsx (3.68 KiB)"
echo "[JSX   ] components/Videos.jsx (360.0 B)"
echo "[JSX   ] components/Categories.jsx (1.73 KiB)"
echo "[JSX   ] components/ChannelSidebar.jsx (990.0 B)"
echo "[JSX   ] components/PlaylistCard.jsx (1.29 KiB)"
echo "[JSX   ] components/VideosLoader.jsx (719.0 B)"
echo "[JSX   ] components/Navbar.jsx (1.55 KiB)"
echo "[JSX   ] components/SearchBar.jsx (1.2 KiB)"
echo "[JSX   ] components/PlaylistSidebar.jsx (1.17 KiB)"
echo "[FOLDER] hooks/"
echo "[JS    ] hooks/useYoutubeContext.js (214.0 B)"
echo "[FOLDER] assets/"
echo "[FOLDER] assets/images/"
echo "[PNG   ] assets/images/screenshot.png (847.36 KiB)"
echo "[PNG   ] assets/images/monkey.png (8.43 KiB)"
echo "[FOLDER] pages/"
echo "[FOLDER] pages/VideoDetails/"
echo "[CSS   ] pages/VideoDetails/VideoDetails.css (350.0 B)"
echo "[JSX   ] pages/VideoDetails/VideoDetails.jsx (4.37 KiB)"
echo "[JSX   ] pages/Error.jsx (547.0 B)"
echo "[JSX   ] pages/PlaylistDetails.jsx (2.7 KiB)"
echo "[JSX   ] pages/ChannelDetails.jsx (3.74 KiB)"
echo "[JSX   ] pages/Search.jsx (1.13 KiB)"
echo "[JSX   ] pages/Home.jsx (2.62 KiB)"
echo "[CSS   ] index.css (797.0 B)"
echo "[JSX   ] main.jsx (231.0 B)"
echo "[JSX   ] App.jsx (1.18 KiB)"
echo ""
echo "End of File List"